markdown: kramdown
include: [_data]

title: Alan Lai
owner: Alan Lai
email: alan.lai@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a Software Engineer with a strong passion for technology. Always eager to play with new technology and figure out how I can make my life easier.
baseurl: "/"
url: "https://blog.alanlai.me" 

social:
  - type: github
    url: https://github.com/anlai
  - type: linkedin
    url: https://www.linkedin.com/in/alan-n-lai/

# Build settings
plugins:
  - jekyll-feed
  
theme: jekyll-theme-cayman

exclude:
  [
    _scripts
  ]